name: cherryish
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.7.0
  flutter_icon_shadow: ^2.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3



  cupertino_icons: ^1.0.2
  http: ^1.2.1
  
  file_picker: ^8.0.0+1
  carousel_slider: ^4.2.1
  cloudinary_public: ^0.23.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/animations/
  - assets/images/
 